version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    container_name: qdrant
    ports:
      - "6333:6333"     # REST / gRPC
      - "6334:6334"     # Web UI
    volumes:
      - ./config/local.yaml:/qdrant/config/local_gpu.yaml
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__GPU__INDEXING=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
