dataset:
  file_path: "evaluation/eval_dataset/locomo/locomo_conv-26.csv"
training:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 8
  epochs: 3
  model_output_path: "trained_model/"
